### ISSUE TITLE
Spring causes Server to crash

### ISSUE THREAD

**Issue by ninjazan420** [njuro/jard#7]
Hey there,

I've tried it with Docker on Windows first, but couldn't get a valid error, except for the server crashes and restarts all the time.
Now, builded with Heroku, the same thing happens: The server seems to start, but crashes right after. It's not even crossing the "after" Spring state.

Heroku log is attached as a log file, but there is no difference to Dockers error :)

Hope you can fix it since I was really enjoying your board!

Greetings
[jard-server-logs-1645567235328.txt](https://github.com/njuro/jard/files/8120474/jard-server-logs-1645567235328.txt)

**Comment by njuro** [comment]
Hello, by looking at the logs it crashes because it's missing AWS credentials and the file storage mode is set to AMAZON_S3 (which is the only sensible option for Heroku deployment, as otherwise you would be losing your data after a short while, due to Heroku ephemeral system). So create an AWS account, set up S3 bucket and then provide the access/secret key and bucket info in the Heroku deployment page. Let me know, if it worked :)

**Comment by ninjazan420** [comment]
Hey, 

thanks for your reply.

Yup, worked, thanks! 
I'll close the issue, but it may be the case that I'll need you again in the future, if I try to make it run on Docker 😋
